name: e3ch-test

on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    services:
      etcd:
        image: soyking/etcd-goreman:v3.5.0
        ports:
          - 2379:12379

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          go test -check.list
          go test -check.vv ./...
